# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QuickStartObjcExampleApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for QuickStartObjcExampleApp
  	pod 'Parse'
  target 'QuickStartObjcExampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  	pod 'Parse'
  end

  target 'QuickStartObjcExampleAppUITests' do
    inherit! :search_paths
    # Pods for testing
  	pod 'Parse'
  end

end
